
from tkinter import *
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.filedialog import askopenfile
from tkinter.messagebox import showinfo
from docx2pdf import convert
from tkinter.filedialog import asksaveasfile
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets_doc")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


win = Tk()

win.geometry("800x400")
win.configure(bg="#FFFFFF")


def openfile():
    global wfile
    wfile = askopenfile(initialdir="/", filetypes=[('Word Files', '*.docx')])


def savename():
    try:
        convert(
            wfile.name,
            r'' + asksaveasfile(mode='w', defaultextension=".pdf",
                                filetypes=[("pdf file", "*.pdf")]).name
        )
        showinfo("Done", "File successfully converted ")
    except:
        showinfo("Error!","Please select a file to convert ")

def windes():
    win.destroy()
    import index

canvas = Canvas(
    win,
    bg="#FFFFFF",
    height=400,
    width=800,
    bd=0,
    highlightthickness=0,
    relief="ridge"
)

canvas.place(x=0, y=0)
canvas.create_rectangle(
    0.0,
    0.0,
    800.0,
    400.0,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    195.0,
    19.0,
    anchor="nw",
    text=" Word to PDF Converter",
    fill="#000000",
    font=("Sen Bold", 36 * -1)
)

canvas.create_text(
    326.0,
    92.0,
    anchor="nw",
    text="Select a File!",
    fill="#000000",
    font=("Sen Regular", 24 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=openfile,
    relief="flat"
)
button_1.place(
    x=339.0,
    y=164.0,
    width=120.0,
    height=36.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=savename,
    relief="flat"
)
button_2.place(
    x=339.0,
    y=230.0,
    width=120.0,
    height=36.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=windes,
    relief="flat"
)
button_3.place(
    x=351.0,
    y=320.0,
    width=100.0,
    height=36.0
)
win.resizable(False, False)
win.mainloop()
